general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# Screen Dimming
listener {
    timeout = 1800                               # 30min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

# Lock Screen
listener {
    timeout = 1980                               # 33min - 3min after dim.
    on-timeout = loginctl lock-session           # lock session.
}

# Screen Off
listener {
    timeout = 2100                               # 35min.
    on-timeout = hyprctl dispatch dpms off       # turn off display.
    on-resume = hyprctl dispatch dpms on         # turn on display.
}

# Actual Suspend
listener {
    timeout = 2700                               # 45min.
    on-timeout = systemctl suspend               # suspend system.
}
